### PR TITLE
UI Updated

### LINKED ISSUE #9: Add themes
**Actual Behaviour**
* No themes are currently supported

**Expected Behaviour**
* Add themes - Light, Dark
* A switch should be added for changing theme

### PR DESCRIPTION
**Pull request by rkishan516**
Fixes #9 
Some color change from Material Design and Button position Updated, Now working in Dark Theme.

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Please send a screenshot for the change. Thanks :)

**Comment by rkishan516** [comment]
screenshot from 2018-12-05 08-31-00
screenshot from 2018-12-05 08-30-56

**Review by akshatnitd — COMMENTED** [review]
I see that you have made the UI in dark mode. That would be nice, but we want to give user the option to use via Light and Dark mode both. Opening an issue for that. In this PR, correcting the spacing and button colors would be fine

**Comment by rkishan516** [comment]
screenshot from 2018-12-08 10-49-22
screenshot from 2018-12-08 10-49-13

**Comment by rkishan516** [comment]
Both Dark and Light Theme are now available

**Comment by rkishan516** [comment]
@Akshat-Jain Please Look at It.

**Review by akshatnitd — APPROVED** [review]
Good work :)

**Pull request merged**
