### PR TITLE
Added New Design For the Extension

### LINKED ISSUE #1: Make new design for the extension
* Make new design for the extension

### PR DESCRIPTION
**Pull request by rkishan516**
Fixes #1 
Changes: Change the main UI of The Extension
screenshot from 2018-12-26 16-54-45
After Update UI look Like This

### CODE REVIEW

**Comment by rkishan516** [comment]
@akshatnitd Please look at this.

**Comment by rkishan516** [comment]
@akshatnitd Please check this.

**Comment by rkishan516** [comment]
@akshatnitd Please look at this PR.

**Review by akshatnitd — COMMENTED** [review]
I don't think this UI would work for us. It occupies a lot of space and conveys lesser information.

**Comment by rkishan516** [comment]
But if we reduce the size of image and make row to two tabs. then ?

**Comment by rkishan516** [comment]
screenshot from 2018-12-28 10-55-29
Something Like this

**Review by akshatnitd — COMMENTED** [review]
screenshot from 2018-12-28 10-56-25
Try out something like this.

Also, the theme switcher should on the top right of the screen.

**Comment by rkishan516** [comment]
screenshot from 2018-12-28 13-35-47
screenshot from 2018-12-28 13-35-54

@akshatnitd any modification require

**Comment by rkishan516** [comment]
screenshot from 2018-12-28 13-53-04
One More Option is available for light theme
Which one is better ?

**Review by akshatnitd — COMMENTED** [review]
Looks better. We don't need any image for background. Use solid colors as previous.

**Comment by rkishan516** [comment]
@akshatnitd 
1. We can use these images.
2. is the Design is okay or not for Tabs ?
3. Why Colors are better than these images ?

**Comment by rkishan516** [comment]
screenshot from 2018-12-28 15-10-48
screenshot from 2018-12-28 15-10-22
@akshatnitd it is the situation after Last two commits

**Comment by rkishan516** [comment]
@akshatnitd Please look at this ?

**Comment by rkishan516** [comment]
@akshatnitd Please check this asap.

**Comment by rkishan516** [comment]
@akshatnitd Please check this.

**Comment by rkishan516** [comment]
@akshatnitd Please check this ASAP.

**Review by akshatnitd — APPROVED** [review]
Looks good! 
You could have used flex for styling, instead of table.

Thanks!

**Pull request merged**
