### PR TITLE
Added Contributing.md File

### LINKED ISSUE #19: Add CONTRIBUTING.md file
This Repo Doesn't Contain CONTRIBUTING.md file.

### PR DESCRIPTION
**Pull request by rkishan516**
Fixes #19 
Added CONTRIBUTING.md file
Because README.md file require this file

### CODE REVIEW

**Comment by rkishan516** [comment]
@akshatnitd Please look at this ASAP.

**Comment by rkishan516** [comment]
@akshatnitd Please look at this.

**Comment by rkishan516** [comment]
@akshatnitd Please Look at this.

**Comment by rkishan516** [comment]
@akshatnitd Please look at this.

**Comment by rkishan516** [comment]
@akshatnitd Please look at this ASAP.

**Comment by akshatnitd** [comment]
Not required now.

**Comment by rkishan516** [comment]
screenshot from 2019-01-09 08-20-43
@akshatnitd It is required here.

**Pull request closed without merging**
