### PR TITLE
Refactor the code

### LINKED ISSUE #3: Refactor the codebase
* Refactor the codebase

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #3

Changes: Refactored the codebase

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
It would be great if you could rename the variables to a more suitable one in this refactoring PR itself. Thanks!

**Comment by samagragupta** [comment]
@akshatnitd Done the required changes

**Comment by samagragupta** [comment]
@akshatnitd I think this PR solved one more issue #5

**Comment by akshatnitd** [comment]
Please resolve conflicts.

**Comment by samagragupta** [comment]
@akshatnitd I am unable to solve the conflicts.
conflicts

**Comment by rkishan516** [comment]
@samagragupta I can resolve the issue. Can i ?

**Comment by rkishan516** [comment]
@samagragupta May I handle this ?

**Comment by akshatnitd** [comment]
@samagragupta If it is okay, @rkishan516 can collaborate with you for this PR.

**Comment by samagragupta** [comment]
@akshatnitd Yeah sure

**Pull request closed without merging**
